### ISSUE TITLE
Custom Options Not Saving

### ISSUE THREAD

**Issue by LordEnder-Kitty** [txnimc/SodiumExtras#10]
The "Display FPS" setting provided by this mod tends to not seem to save properly and I keep having to re-disable it.

**Comment by LordEnder-Kitty** [comment]
I've noticed this issue with a few other settings from this mod as well.

**Comment by HoYin1600p** [comment]
Borderless windowed mode not persistent after restart.

**Comment by LordEnder-Kitty** [comment]
> Borderless windowed mode not persistent after restart.

Yeah. All the settings are just not being saved after restarting the game. Did they forget to actually save the config? lol

**Comment by nthxny** [comment]
i forgor 💀

**Comment by nthxny** [comment]
should be fixed
