### ISSUE TITLE
[1.20.1]Crash after clicking at Video Settings button 

### ISSUE THREAD

**Issue by MihanDeNoob** [txnimc/SodiumExtras#11]
crashlog: https://mclo.gs/Q3Xna7Q

**Comment by LordEnder-Kitty** [comment]
Looks like it's related to Embeddium. 
![image](https://github.com/user-attachments/assets/6f954687-2c72-4ff0-8fdf-6b00e14a5d46)

**Comment by MihanDeNoob** [comment]
> Looks like it's related to Embeddium.

How is that even possible?? oO
I dont use Embeddium oO I only had [Sodium Extra](https://modrinth.com/mod/sodium-extra) and [Reese's Sodium Options](https://modrinth.com/mod/reeses-sodium-options) both of which i disabled to test it (it wasnt them)

**Comment by ayuwooh** [comment]
After testing mods, it's incompatibility with More Culling.
