### ISSUE TITLE
Embeddium 1.20.1+ compatibility problem.

### ISSUE THREAD

**Issue by Sebastian-Java** [txnimc/SodiumExtras#2]
My game is crashing because this needs TexTrue's Embeddium options, the thing is, Embeddium now has TEO built-in. And when I load TEO, the game crashes because it is not compatible. Is there any solution for this? And if not, consider this problem while developing new versions.

**Comment by JuanTaco666** [comment]
I am having the same issue, would very much appreciate someone to look at this

**Comment by nthxny** [comment]
latest 1.20 version should work now.
