### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by Ciellix** [txnimc/SodiumExtras#20]
I was opening the controls page, and I pressed F11 too go in to full screen and the game crashed with the following error https://mclo.gs/HDw5mVP I am guessing its caused by this mod, as it said SodiumExtras, if I am wrong my bad, thanks for any help
Neoforge 1.21.1-21.179 Sodium/Embeddium Extras version 1.0.6

**Comment by Ciellix** [comment]
Its likely connected too this issue https://github.com/txnimc/SodiumOptionsAPI/issues/15#issue-2666324403

**Comment by nthxny** [comment]
should be fixed in latest release of Sodium Options API

**Comment by Ciellix** [comment]
> should be fixed in latest release of Sodium Options API

alright, thanks
